version: '3.7'

services:
  server:
    container_name: webapp-test
    build:
      context: ../
      dockerfile: docker/Dockerfile
    volumes:
      - '../:/app'
      - '/app/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
